title: Sysctl Theme Demo
description: A clean, fast, and SEO-friendly Jekyll theme demo
baseurl: ""
url: ""

# Set the theme to the local theme
theme: sysctl-theme
# If the above doesn't work, try:
# theme: jekyll-theme-sysctl

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
paginate_path: "/page/:num/"

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Articles
    url: /articles
  - title: Tags
    url: /tags
  - title: Contact
    url: /contact

# Social links
social:
  github: awcodify
  twitter: awcodify
  linkedin: awcodify
  email: awcodify@gmail.com

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Content settings
excerpt_separator: <!--more-->

# Include directories that would otherwise be excluded
include: ["_layouts", "_includes", "_sass"]