# Main configuration for Sysctl Theme

# Site settings
name: Sysctl Theme
title: Sysctl Theme
email: awcodify@gmail.com
description: >-
  A clean, fast and SEO-friendly Jekyll theme focused on technical content and code readability.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # for local testing

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
paginate_path: "/page/:num/"

# Theme-specific settings
date_format: "%b %-d, %Y" # e.g. May 5, 2025

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Articles
    url: /articles
  - title: Tags
    url: /tags
  - title: Contact
    url: /contact

# Social links
social:
  github: awcodify
  twitter: # your Twitter handle
  linkedin: # your LinkedIn username
  email: awcodify@gmail.com

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Content settings
excerpt_separator: <!--more-->

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - example/