blank_issues_enabled: false
contact_links:
  - name: Arsxy Theme Discussions
    url: https://github.com/awcodify/arsxy-theme/discussions
    about: Please ask and answer questions here.
  - name: Arsxy Theme Documentation
    url: https://github.com/awcodify/arsxy-theme/tree/main/docs
    about: Check our documentation for answers to common questions.
